### PR TITLE
Replace f1 stats with todo app

### PR DESCRIPTION
**Pull request by zInnovationLab**
This one works better with MongoDB

### CODE REVIEW

**Comment by animeshsingh** [comment]
Will that change anything in the diagram, or the flow we have in the wiki. Please check ocne

**Comment by zInnovationLab** [comment]
Yes, the diagram will now have 2 containers - 1 MongoDB and 1 node.js. I'm going to add screenshots and debugging hints etc soon.

**Comment by animeshsingh** [comment]
ah - we should get these things communicated sooner

**Comment by animeshsingh** [comment]
Is it still called MEAN stack?

**Comment by zInnovationLab** [comment]
Yes. Still MEAN. Has Mongo Express Angular on Node

**Pull request merged**
